name: ramips-k2p

on:
  schedule:
    - cron: '0 4 1 * *'  # K2P at 04:00 UTC
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      device_name: phicomm-k2p
      target: ramips
      subtarget: mt7621
      profile: phicomm_k2p
      lan_ip: 192.168.123.5
      config_method: single-file
      wifi_ssid: NETGEAR_5G
      wifi_encryption: psk2
      wifi_key: "13882020269"
      wifi_cipher: ccmp
