name: rockchip

on:
  schedule:
    - cron: '0 0 1 * *'  # R2S at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      device_name: r2s
      target: rockchip
      subtarget: armv8
      profile: friendlyarm_nanopi_r2s
      lan_ip: 192.168.123.2
      config_method: multi-file
