name: Sync Upstream
on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨3点自动同步
  push:
    branches: [ master ]

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
    # 代码检出
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整提交历史

    # 配置Git身份（避免空提交报错）
    - name: Setup Git identity
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # 添加上游仓库
    - name: Add upstream
      run: |
        git remote add upstream https://github.com/immortalwrt/immortalwrt.git
        git fetch upstream

    # 合并更新
    - name: Merge upstream
      run: |
        git checkout master
        git merge upstream/master --no-edit  # 自动接受合并信息
        git push origin master
